<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaContable.Entities\SistemaContable.Entities.csproj" />
    <ProjectReference Include="..\SistemaContable.Services\SistemaContable.Services.csproj" />
  </ItemGroup>

</Project>
